# Generated by Django 3.1.5 on 2021-02-03 11:06

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210203_1105'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(user=django.db.models.expressions.F('following')), name='no_follow_yourself'),
        ),
    ]
