# Generated by Django 3.1.5 on 2021-01-27 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20210127_1337"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Необязательно",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="api.group",
                verbose_name="Группа",
            ),
        ),
    ]
