# Generated by Django 3.1.5 on 2021-02-03 11:10

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210203_1106'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='no_follow_yourself',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('following')), name='no_follow_yourself'),
        ),
    ]
