# Generated by Django 3.1.5 on 2021-02-02 10:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_auto_20210131_1536'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='follow',
            index_together={('user', 'following')},
        ),
    ]
