# Generated by Django 3.1.5 on 2021-02-02 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210202_1055'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='follow',
            index_together=set(),
        ),
    ]
